spring.application.name=backend

spring.datasource.url=jdbc:postgresql://postgres:5432/vibecheck
spring.datasource.password=postgres
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop