services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_4d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vibecheck
    ports:
      - "5432:5432"
  backend:
    image:  ghcr.io/sneeld22/vibechecksypdocker:latest
    ports:
     - "8080:8080"